parameters:
    ist1.channel.request_maker.class: Ist1\RequestMaker\BasicRequestMaker
    ist1.channel.class: Ist1\ChannelBundle\Service\Channel
    twig.controller.exception.class: Ist1\ChannelBundle\Controller\ChannelExceptionController

services:
    ist1_channel.request_maker:
        class: %ist1.channel.request_maker.class%

    ist1_channel.channel:
        class: %ist1.channel.class%
        arguments: [@jms_serializer.serializer, @ist1_channel.request_maker, %channel_url%, %channel_format%]